### ISSUE TITLE
Create a contributing.md file 

### ISSUE THREAD

**Issue by itisaby** [acm-iem/Twitter-Bot#6]
The file must contain all the guidelines required for the contributors while contributing to the project.

**Comment by MohammedHamzaMalik** [comment]
Hey, I would like to work on this issue.

**Comment by itisaby** [comment]
Go ahead @MohammedHamzaMalik 
while creating the PR also link the issue :)

**Comment by vasav-prashar** [comment]
sir i thought it was open

**Comment by MohammedHamzaMalik** [comment]
@itisaby Sure

**Comment by itisaby** [comment]
hey @vasav-prashar can I assign you on other projects contributing.md file ?
You have done a cool PR
